export default {
    LOGIN: "login",
    LOGOUT: "logout",
    GET_USER_PROFILE: "getUserProfile",
    GET_GEDUNG_FACILITIES: "getGedungFacilities",
    SAVE_GEDUNG_DATA: "saveGedungData",
    UPDATE_GEDUNG_DATA: "updateGedungData",
    GET_GEDUNG_DATA: "getGedungData",
    GET_DETAIL_GEDUNG_DATA: "getDetailGedungData",
    GET_ROOM_FACILITIES: "getRoomFacilities",
    GET_ROOMS: "getRooms",
    UPLOAD_IMAGE: "uploadImage",
    GET_BUILDINGS_ONLY: "getBuildingsOnly",
    // Master Data - Program Studi
    GET_PROGRAM_STUDI: "getProgramStudi",
    CREATE_PROGRAM_STUDI: "createProgramStudi",
    UPDATE_PROGRAM_STUDI: "updateProgramStudi",
    DELETE_PROGRAM_STUDI: "deleteProgramStudi",
    // Master Data - Kelas
    GET_KELAS: "getKelas",
    CREATE_KELAS: "createKelas",
    UPDATE_KELAS: "updateKelas",
    DELETE_KELAS: "deleteKelas",
    // Settings - SKS Setting
    GET_SKS_SETTING: "getSksSetting",
    UPDATE_SKS_SETTING: "updateSksSetting",
    // Settings - Operasional Schedule
    GET_OPERASIONAL_SCHEDULE: "getOperasionalSchedule",
    UPDATE_OPERASIONAL_SCHEDULE: "updateOperasionalSchedule",
    // Master Data - Mata Kuliah
    GET_MATA_KULIAH: "getMataKuliah",
    CREATE_MATA_KULIAH: "createMataKuliah",
    UPDATE_MATA_KULIAH: "updateMataKuliah",
    DELETE_MATA_KULIAH: "deleteMataKuliah",
    // Master Data - Mahasiswa
    GET_MAHASISWA: "getMahasiswa",
    CREATE_MAHASISWA: "createMahasiswa",
    UPDATE_MAHASISWA: "updateMahasiswa",
    DELETE_MAHASISWA: "deleteMahasiswa",
    // Master Data - Dosen
    GET_DOSEN: "getDosen",
    CREATE_DOSEN: "createDosen",
    UPDATE_DOSEN: "updateDosen",
    DELETE_DOSEN: "deleteDosen",
    // Master Data - Periode
    GET_PERIODE: "getPeriode",
    CREATE_PERIODE: "createPeriode",
    UPDATE_PERIODE: "updatePeriode",
    DELETE_PERIODE: "deletePeriode",
    // Master Data - Hari Libur
    GET_HARI_LIBUR: "getHariLibur",
    CREATE_HARI_LIBUR: "createHariLibur",
    UPDATE_HARI_LIBUR: "updateHariLibur",
    DELETE_HARI_LIBUR: "deleteHariLibur",
    // Master Data - Menus
    GET_MENUS: "getMenus",
    CREATE_MENU: "createMenu",
    UPDATE_MENU: "updateMenu",
    DELETE_MENU: "deleteMenu",
    // Master Data - Role Menus
    GET_ROLE_MENUS: "getRoleMenus",
    UPDATE_ROLE_MENUS: "updateRoleMenus",
    GET_APP_MENU: "getAppMenu",
    GET_NOTIFICATIONS: "getNotifications",
    GET_UNREAD_NOTIFICATION_COUNT: "getUnreadNotificationCount",
    MARK_ALL_NOTIFICATIONS_READ: "markAllNotificationsRead",
    MARK_NOTIFICATION_READ: "markNotificationRead",
    SUBMIT_PENGAJUAN: "submitPengajuan",
    GET_LIST_PENGAJUAN: "getListPengajuan",
    GET_DETAIL_PENGAJUAN: "getDetailPengajuan",
    GET_WORKFLOW_HISTORY: "getWorkflowHistory",
}
