const apiUrl = {
    LOGIN: "/login",
    LOGOUT: "/logout",
    USER_PROFILE: "/user/profile",
    GEDUNG_FACILITIES: "/building/facilities",
    SAVE_GEDUNG: "/building/buildings",
    UPDATE_GEDUNG: "/building/buildings",
    GET_GEDUNG: "/building/buildings",
    GET_DETAIL_GEDUNG: "/building/buildings",
    GET_ROOM_FACILITIES: "/building/rooms",
    GET_ROOMS: "/building/rooms",
    UPLOAD_IMAGE: "/documents/upload",
    GET_BUILDINGS_ONLY: "/building/buildings-simple",
    // Master Data - Program Studi
    PROGRAM_STUDI: "/master-data/program-studi",
    KELAS: "/master-data/kelas",
    SKS_SETTING: "/master-data/sks-setting",
    OPERASIONAL_SCHEDULE: "/master-data/operasional-schedule",
    MATA_KULIAH: "/master-data/mata-kuliah",
    MAHASISWA: "/master-data/mahasiswa",
    DOSEN: "/master-data/dosen",
    PERIODE: "/master-data/periodes",
    HARI_LIBUR: "/master-data/hari-libur",
    MENU: "/master-data/menus",
    ROLE_MENU: "/master-data/role-menus",
    SUBMIT_PENGAJUAN: "/pengajuan/peminjaman",
    GET_DETAIL_PENGAJUAN: "/pengajuan/peminjaman",
    GET_WORKFLOW_HISTORY: "/pengajuan/peminjaman",
};
export default apiUrl;
