import ACTIONS from "@/core/plugins/constants/actions.js";
const namespaces = {
    AUTH: "auth/",
    GEDUNG: "gedung/",
    MASTER_DATA: "masterData/",
    SETTINGS: "settings/",
    LIST_PENGAJUAN: "listPengajuan/",
    DASHBOARD: "dashboard/",
    PENJADWALAN: "penjadwalan/",
};

export default {
    LOGIN: namespaces.AUTH + ACTIONS.LOGIN,
    LOGOUT: namespaces.AUTH + ACTIONS.LOGOUT,
    GET_USER_PROFILE: namespaces.AUTH + ACTIONS.GET_USER_PROFILE,
    GET_APP_MENU: namespaces.AUTH + ACTIONS.GET_APP_MENU,
    GET_GEDUNG_FACILITIES: namespaces.GEDUNG + ACTIONS.GET_GEDUNG_FACILITIES,
    SAVE_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.SAVE_GEDUNG_DATA,
    UPDATE_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.UPDATE_GEDUNG_DATA,
    GET_DASHBOARD_DATA: namespaces.DASHBOARD + ACTIONS.GET_DASHBOARD_DATA,
    GET_NOTIFICATIONS: namespaces.DASHBOARD + ACTIONS.GET_NOTIFICATIONS,
    GET_UNREAD_NOTIFICATION_COUNT: namespaces.DASHBOARD + ACTIONS.GET_UNREAD_NOTIFICATION_COUNT,
    MARK_ALL_NOTIFICATIONS_READ: namespaces.DASHBOARD + ACTIONS.MARK_ALL_NOTIFICATIONS_READ,
    MARK_NOTIFICATION_READ: namespaces.DASHBOARD + ACTIONS.MARK_NOTIFICATION_READ,
    GET_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.GET_GEDUNG_DATA,
    GET_DETAIL_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.GET_DETAIL_GEDUNG_DATA,
    GET_ROOM_FACILITIES: namespaces.GEDUNG + ACTIONS.GET_ROOM_FACILITIES,
    GET_ROOMS: namespaces.PENJADWALAN + ACTIONS.GET_ROOMS,
    GET_ROOMS_BY_GEDUNG: namespaces.GEDUNG + ACTIONS.GET_ROOMS,
    UPLOAD_IMAGE: namespaces.GEDUNG + ACTIONS.UPLOAD_IMAGE,
    GET_BUILDINGS_ONLY: namespaces.GEDUNG + ACTIONS.GET_BUILDINGS_ONLY,
    // Master Data - Program Studi
    GET_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.GET_PROGRAM_STUDI,
    CREATE_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.CREATE_PROGRAM_STUDI,
    UPDATE_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.UPDATE_PROGRAM_STUDI,
    DELETE_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.DELETE_PROGRAM_STUDI,
    // Settings - Kelas
    GET_KELAS: namespaces.SETTINGS + ACTIONS.GET_KELAS,
    CREATE_KELAS: namespaces.SETTINGS + ACTIONS.CREATE_KELAS,
    UPDATE_KELAS: namespaces.SETTINGS + ACTIONS.UPDATE_KELAS,
    DELETE_KELAS: namespaces.SETTINGS + ACTIONS.DELETE_KELAS,
    // Settings - SKS Setting
    GET_SKS_SETTING: namespaces.SETTINGS + ACTIONS.GET_SKS_SETTING,
    UPDATE_SKS_SETTING: namespaces.SETTINGS + ACTIONS.UPDATE_SKS_SETTING,
    // Settings - Operasional Schedule
    GET_OPERASIONAL_SCHEDULE: namespaces.SETTINGS + ACTIONS.GET_OPERASIONAL_SCHEDULE,
    UPDATE_OPERASIONAL_SCHEDULE: namespaces.SETTINGS + ACTIONS.UPDATE_OPERASIONAL_SCHEDULE,
    // Master Data - Mata Kuliah
    GET_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.GET_MATA_KULIAH,
    CREATE_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.CREATE_MATA_KULIAH,
    UPDATE_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.UPDATE_MATA_KULIAH,
    DELETE_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.DELETE_MATA_KULIAH,
    // Master Data - Mahasiswa
    GET_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.GET_MAHASISWA,
    CREATE_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.CREATE_MAHASISWA,
    UPDATE_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.UPDATE_MAHASISWA,
    DELETE_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.DELETE_MAHASISWA,
    // Master Data - Dosen
    GET_DOSEN: namespaces.MASTER_DATA + ACTIONS.GET_DOSEN,
    CREATE_DOSEN: namespaces.MASTER_DATA + ACTIONS.CREATE_DOSEN,
    UPDATE_DOSEN: namespaces.MASTER_DATA + ACTIONS.UPDATE_DOSEN,
    DELETE_DOSEN: namespaces.MASTER_DATA + ACTIONS.DELETE_DOSEN,
    // Master Data - Periode
    GET_PERIODE: namespaces.MASTER_DATA + ACTIONS.GET_PERIODE,
    CREATE_PERIODE: namespaces.MASTER_DATA + ACTIONS.CREATE_PERIODE,
    UPDATE_PERIODE: namespaces.MASTER_DATA + ACTIONS.UPDATE_PERIODE,
    DELETE_PERIODE: namespaces.MASTER_DATA + ACTIONS.DELETE_PERIODE,
    // Master Data - Kelas Mata Kuliah
    GET_KELAS_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.GET_KELAS_MATA_KULIAH,
    CREATE_KELAS_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.CREATE_KELAS_MATA_KULIAH,
    UPDATE_KELAS_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.UPDATE_KELAS_MATA_KULIAH,
    DELETE_KELAS_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.DELETE_KELAS_MATA_KULIAH,
    // Settings - Hari Libur
    GET_HARI_LIBUR: namespaces.SETTINGS + ACTIONS.GET_HARI_LIBUR,
    CREATE_HARI_LIBUR: namespaces.SETTINGS + ACTIONS.CREATE_HARI_LIBUR,
    UPDATE_HARI_LIBUR: namespaces.SETTINGS + ACTIONS.UPDATE_HARI_LIBUR,
    DELETE_HARI_LIBUR: namespaces.SETTINGS + ACTIONS.DELETE_HARI_LIBUR,
    // Settings - Menus
    GET_MENUS: namespaces.SETTINGS + ACTIONS.GET_MENUS,
    CREATE_MENU: namespaces.SETTINGS + ACTIONS.CREATE_MENU,
    UPDATE_MENU: namespaces.SETTINGS + ACTIONS.UPDATE_MENU,
    DELETE_MENU: namespaces.SETTINGS + ACTIONS.DELETE_MENU,
    // Settings - Role Menus
    GET_ROLE_MENUS: namespaces.SETTINGS + ACTIONS.GET_ROLE_MENUS,
    UPDATE_ROLE_MENUS: namespaces.SETTINGS + ACTIONS.UPDATE_ROLE_MENUS,
    // List Pengajuan
    SUBMIT_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.SUBMIT_PENGAJUAN,
    GET_LIST_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.GET_LIST_PENGAJUAN,
    GET_DETAIL_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.GET_DETAIL_PENGAJUAN,
    GET_WORKFLOW_HISTORY: namespaces.LIST_PENGAJUAN + ACTIONS.GET_WORKFLOW_HISTORY,
    APPROVE_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.APPROVE_PENGAJUAN,
    REJECT_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.REJECT_PENGAJUAN,
    REVISION_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.REVISION_PENGAJUAN,
    UPDATE_PENGAJUAN: namespaces.LIST_PENGAJUAN + ACTIONS.UPDATE_PENGAJUAN,
    // Penjadwalan Ujian
    GET_JADWAL:           namespaces.PENJADWALAN + ACTIONS.GET_JADWAL,
    GET_JADWAL_DRAFT:     namespaces.PENJADWALAN + ACTIONS.GET_JADWAL_DRAFT,
    GENERATE_JADWAL:      namespaces.PENJADWALAN + ACTIONS.GENERATE_JADWAL,
    SAVE_JADWAL_DRAFT:    namespaces.PENJADWALAN + ACTIONS.SAVE_JADWAL_DRAFT,
    UPDATE_JADWAL_ROW:    namespaces.PENJADWALAN + ACTIONS.UPDATE_JADWAL_ROW,
    SAVE_JADWAL_PERMANEN: namespaces.PENJADWALAN + ACTIONS.SAVE_JADWAL_PERMANEN,
    DELETE_JADWAL_DRAFT:  namespaces.PENJADWALAN + ACTIONS.DELETE_JADWAL_DRAFT,
};
