import ACTIONS from "@/core/plugins/constants/actions.js";
const namespaces = {
    AUTH: "auth/",
    GEDUNG: "gedung/",
    MASTER_DATA: "masterData/",
    SETTINGS: "settings/",
};

export default {
    LOGIN: namespaces.AUTH + ACTIONS.LOGIN,
    LOGOUT: namespaces.AUTH + ACTIONS.LOGOUT,
    GET_USER_PROFILE: namespaces.AUTH + ACTIONS.GET_USER_PROFILE,
    GET_GEDUNG_FACILITIES: namespaces.GEDUNG + ACTIONS.GET_GEDUNG_FACILITIES,
    SAVE_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.SAVE_GEDUNG_DATA,
    UPDATE_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.UPDATE_GEDUNG_DATA,
    GET_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.GET_GEDUNG_DATA,
    GET_DETAIL_GEDUNG_DATA: namespaces.GEDUNG + ACTIONS.GET_DETAIL_GEDUNG_DATA,
    GET_ROOM_FACILITIES: namespaces.GEDUNG + ACTIONS.GET_ROOM_FACILITIES,
    UPLOAD_IMAGE: namespaces.GEDUNG + ACTIONS.UPLOAD_IMAGE,
    GET_BUILDINGS_ONLY: namespaces.GEDUNG + ACTIONS.GET_BUILDINGS_ONLY,
    // Master Data - Program Studi
    GET_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.GET_PROGRAM_STUDI,
    CREATE_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.CREATE_PROGRAM_STUDI,
    UPDATE_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.UPDATE_PROGRAM_STUDI,
    DELETE_PROGRAM_STUDI: namespaces.MASTER_DATA + ACTIONS.DELETE_PROGRAM_STUDI,
    // Settings - Kelas
    GET_KELAS: namespaces.SETTINGS + ACTIONS.GET_KELAS,
    CREATE_KELAS: namespaces.SETTINGS + ACTIONS.CREATE_KELAS,
    UPDATE_KELAS: namespaces.SETTINGS + ACTIONS.UPDATE_KELAS,
    DELETE_KELAS: namespaces.SETTINGS + ACTIONS.DELETE_KELAS,
    // Master Data - Mata Kuliah
    GET_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.GET_MATA_KULIAH,
    CREATE_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.CREATE_MATA_KULIAH,
    UPDATE_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.UPDATE_MATA_KULIAH,
    DELETE_MATA_KULIAH: namespaces.MASTER_DATA + ACTIONS.DELETE_MATA_KULIAH,
    // Master Data - Mahasiswa
    GET_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.GET_MAHASISWA,
    CREATE_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.CREATE_MAHASISWA,
    UPDATE_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.UPDATE_MAHASISWA,
    DELETE_MAHASISWA: namespaces.MASTER_DATA + ACTIONS.DELETE_MAHASISWA,
    // Master Data - Dosen
    GET_DOSEN: namespaces.MASTER_DATA + ACTIONS.GET_DOSEN,
    CREATE_DOSEN: namespaces.MASTER_DATA + ACTIONS.CREATE_DOSEN,
    UPDATE_DOSEN: namespaces.MASTER_DATA + ACTIONS.UPDATE_DOSEN,
    DELETE_DOSEN: namespaces.MASTER_DATA + ACTIONS.DELETE_DOSEN,
};
